### PR TITLE
Added initial draft of newsletter for April

### PR DESCRIPTION
**Pull request by RangerMauve**
Hey all, I'd like to get a newsletter out at the beginning of May with some stuff from April. Here's a draft with a few items that I could think of.

I'd also like to mention something related to [planning](https://github.com/datproject/planning/issues) and the [working group](https://github.com/datprotocol/working-group/) but I'm not sure how to phrase it. Something like "Follow these repos to stay up to date on upcoming improvements to the spec"?

Also, if anyone has links or news that we could add, please post them here. :)

Gonna try to get this out on Friday. :)

CC @hossameldeen (maybe you could give a brief summary of the project you linked to before so we can include it in the newsletter)

### CODE REVIEW

**Comment by arj03** [comment]
Not exactly what the scope of this newsletters is, but we recently added [support for dat](http://between-two-worlds.dk:8807/%25rbQ6ggItkXWd3EPZ%2FG6zIOIN2r%2Bd14v2egEVqvxbXoo%3D.sha256) to [patchbay](https://github.com/ssbc/patchbay) for better integration between [ssb](https://github.com/ssbc/) and dat.

**Comment by RangerMauve** [comment]
@arj03 That's awesome! We should definitely have that in the newsletter! :D

**Comment by arj03** [comment]
Great :) Some more background on [how](http://between-two-worlds.dk:8807/%jDEB8e31x+tIzBql6b8dGmhn58+t9kytYXi5X15CSi4=.sha256) this could be used

**Comment by RangerMauve** [comment]
@arj03 How does that look to you? :)

**Comment by arj03** [comment]
Excellent, thanks :)

**Comment by hossameldeen** [comment]
Thanks for remembering me, @RangerMauve!

I'm not sure if you want it to be a one-liner or a few sentences, but here it is & feel free to ask me to shorten it.

> ## [Transparent Salaries](https://github.com/hossameldeen/transparent-salaries) by [Hossam El-Deen](https://github.com/hossameldeen)
> 
> A **social network** for sharing **anonymized** salaries. A [Beaker Browser](https://beakerbrowser.com/) website where each user:
> 
> - **Posts _anonymized_ salaries known to them**, e.g., of people from their network, after taking their permission.
> - **Specifies other users they trust** to be honest and write true salaries.
> 
> [Hossam El-Deen](https://github.com/hossameldeen) has been working on it for 6 months and has actually released it last December. An experiment in new software business models, it's [available on Gumroad](https://gumroad.com/l/gDDIe) for $7. The code is [open-source](https://github.com/hossameldeen/transparent-salaries) as well, but definitely [not freemium](https://github.com/hossameldeen/transparent-salaries/blob/master/LICENSE).
> 
> It's been in a limbo state for some time now as it got no traction. But if you happen to find it useful to you, feel free to [buy a copy](https://gumroad.com/l/gDDIe) :-)
> 
> **Ad:** Hossam is currently looking for a remote job, related to dat or not. You can reach out to him [here](https://forms.gle/S8ZwPGH8pVprfjvd8).

### Markdown:

```
## [Transparent Salaries](https://github.com/hossameldeen/transparent-salaries) by [Hossam El-Deen](https://github.com/hossameldeen)

A **social network** for sharing **anonymized** salaries. A [Beaker Browser](https://beakerbrowser.com/) website where each user:

- **Posts _anonymized_ salaries known to them**, e.g., of people from their network, after taking their permission.
- **Specifies other users they trust** to be honest and write true salaries.

[Hossam El-Deen](https://github.com/hossameldeen) has been working on it for 6 months and has actually released it last December. An experiment in new software business models, it's [available on Gumroad](https://gumroad.com/l/gDDIe) for $7. The code is [open-source](https://github.com/hossameldeen/transparent-salaries) as well, but definitely [not freemium](https://github.com/hossameldeen/transparent-salaries/blob/master/LICENSE).

It's been in a limbo state for some time now as it got no traction. But if you happen to find it useful to you, feel free to [buy a copy](https://gumroad.com/l/gDDIe) :-)

**Ad:** Hossam is currently looking for a remote job, related to dat or not. You can reach out to him [here](https://forms.gle/S8ZwPGH8pVprfjvd8).
```

Feel free to omit the ad in the end if you feel it irrelevant to the newsletter.

Again, please, take total freedom in suggesting changes or even changing it to a one-liner.

**Comment by karissa** [comment]
@hossameldeen I wonder if you could post your description of your website somewhere so we could link to it in the newsletter under "new community projects" ? There's already a lot of text in this month's newsletter and I'm afraid that it'll be too long to add all of that. Thank you!

**Comment by rjsteinert** [comment]
Mentioning the upcoming DWeb camp (https://dwebcamp.org/) would be cool. I'm on their Open Dialogue call right now and they are talking about how they will not have Internet at the conf but will have a mesh network, seeing it as an interesting challenge for P2P projects to work over offline LAN.

**Comment by rjsteinert** [comment]
Also Offline Camp announced dates! w00t! Another fun outdoor adventure for folks who love offline P2P http://offlinefirst.org/camp/

**Comment by RangerMauve** [comment]
@hossameldeen I agree with Karissa, a link to a blog post would probably be easier to keep things succinct. 

@rjsteinert I think we should put offline camp in the next one since it's a lot further away. :o

**Comment by hossameldeen** [comment]
@karissa @RangerMauve Yup, sure :)

Just link to the GitHub repo, please: https://github.com/hossameldeen/transparent-salaries

**Comment by RangerMauve** [comment]
Hi @hossameldeen I don't think that paid projects are in the spirit of the newsletter. It might be better to go through traditional advertising avenues for that. :)

**Comment by RangerMauve** [comment]
Cool, gonna merge what we have so far and draft up the newsletter in mailchimp. We'll release it on Tuesday since that's a better day to get people to read it.

**Comment by hossameldeen** [comment]
@RangerMauve I highly disagree, but won't argue here in order to not let the PR go off topic. Opened an issue #6.

By the way, I don't mind merging the PR at all. I understand there was no time to discuss such point :-)

**Comment by joehand** [comment]
See newsletter here: https://mailchi.mp/779e4e327572/dat-project-newsletter-spring-2019

Changed a few items:

* Updated language around Berlin event:
  * removed "hack" language 
  * updated language around sponsoring b/c sponsored by multiple orgs
*  Updated language around Samsung funding
  * The funding was a grant to Dat's OpenCollective, not hyperdivision

**Pull request merged**
